// <auto-generated />
namespace ECommerceLiteDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_quantitytur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_quantitytur));
        
        string IMigrationMetadata.Id
        {
            get { return "202204191134120_mig_quantitytur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
